/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleAdd: typeof import('./src/components/background/models/ArticleAdd.vue')['default']
    ArticleEdit: typeof import('./src/components/background/models/ArticleEdit.vue')['default']
    ArticlePanel: typeof import('./src/components/background/models/ArticlePanel.vue')['default']
    Background: typeof import('./src/components/background/Background.vue')['default']
    BasicSearch: typeof import('./src/components/panel/models/search/BasicSearch.vue')['default']
    ChildComments: typeof import('./src/components/background/models/ChildComments.vue')['default']
    Discuss: typeof import('./src/components/panel/models/discussion/Discuss.vue')['default']
    DiscussionPanel: typeof import('./src/components/background/models/DiscussionPanel.vue')['default']
    EasySearch: typeof import('./src/components/panel/models/search/EasySearch.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Foot: typeof import('./src/components/panel/Foot.vue')['default']
    Head: typeof import('./src/components/panel/Head.vue')['default']
    Home: typeof import('./src/components/panel/Home.vue')['default']
    Login: typeof import('./src/components/loginAndRegister/Login.vue')['default']
    Main: typeof import('./src/components/panel/models/article/Main.vue')['default']
    MemberAdd: typeof import('./src/components/background/models/MemberAdd.vue')['default']
    MemberPanel: typeof import('./src/components/background/models/MemberPanel.vue')['default']
    ProfessionalSearch: typeof import('./src/components/panel/models/search/ProfessionalSearch.vue')['default']
    RankList: typeof import('./src/components/panel/models/main/RankList.vue')['default']
    Register: typeof import('./src/components/loginAndRegister/Register.vue')['default']
    RightMain: typeof import('./src/components/panel/models/main/RightMain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResult: typeof import('./src/components/panel/models/search/SearchResult.vue')['default']
    UpCard: typeof import('./src/components/panel/models/main/UpCard.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
